apiVersion: apps/v1
kind: Deployment
metadata:
  name: coms-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coms-ui
  template:
    metadata:
      labels:
        app: coms-ui
    spec:
      containers:
        - name: coms-ui
          image: sivajisaha/coms-ui:0.1
          ports:
            - containerPort: 8080
          env:
            - name: spring.datasource.url
              value: "jdbc:postgresql://192.168.0.133:5432/coms_db"
            - name: coms.app.code
              value: "COMS_BPM_KUBE"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: coms-ui
spec:
  type: NodePort
  selector:
    app: coms-ui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080