apiVersion: apps/v1
kind: Deployment
metadata:
  name: coms-bpm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coms-bpm-api
  template:
    metadata:
      labels:
        app: coms-bpm-api
    spec:
      containers:
        - name: coms-bpm-api
          image: sivajisaha/coms-bpm-api:0.1
          ports:
            - containerPort: 8082
          env:
            - name: spring.datasource.url
              value: "jdbc:postgresql://192.168.0.133:5432/coms_db"
            - name: spring.kafka.bootstrap-servers
              value: "192.168.0.133:9092"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: coms-bpm-api
spec:
  type: NodePort
  selector:
    app: coms-bpm-api
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31082